sudo: required
services:
  - docker
language: bash
jobs:
  include:
    - stage: frontend-build
      script:
        - docker build -t fluxweb/frontend ./frontend
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - docker tag fluxweb/frontend fluxweb/frontend:$TRAVIS_TAG &&
          docker push fluxweb/frontend:$TRAVIS_TAG &&
          docker push fluxweb/frontend:latest
    - stage: backend-build
      script:
        - docker build -t fluxweb/backend ./backend
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          docker push fluxweb/backend:$TRAVIS_TAG &&
          docker push fluxweb/backend:latest
